# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/ALPHA.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/BETA.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/DELTA.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/EPSILON.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/ETA.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/GAMMA.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/IOTA.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/KAPPA.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/LAMBDA.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/MU.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/OMICRON-BA1.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/OMICRON-BA2.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/OMICRON-BA3.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/OTHER.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/THETA.COMBINED.metadata.tsv
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/ZETA.COMBINED.metadata.tsv

# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/ALPHA.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/BETA.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/DELTA.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/EPSILON.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/ETA.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/GAMMA.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/IOTA.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/KAPPA.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/LAMBDA.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/MU.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/OMICRON-BA1.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/OMICRON-BA2.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/OMICRON-BA3.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/OTHER.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/THETA.COMBINED.sequences.fasta
# curl -O https://genome.med.nyu.edu/results/external/dellicour/NYULH2022/ZETA.COMBINED.sequences.fasta
